language: rust

sudo: required

matrix:
  include:
    - rust: 1.32.0
      env: FEATURES="blas serde-1 docs"
    - rust: stable
      env: FEATURES="blas serde-1 docs"
    - rust: beta
      env: FEATURES="blas serde-1 docs"
    - rust: nightly
      env: FEATURES="blas serde-1 docs nightly"
  allow_failures:
    - rust: beta
    - rust: nightly

env:
  global:
    - RUSTFLAGS="-D warnings"

cache: cargo

addons:
  apt:
    update: true
    packages:
      - libopenblas-dev
      - gfortran
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev
      - libiberty-dev
      - libgsl0-dev

before_script:
  - ./ci/before_script.sh

script:
  - ./ci/script.sh

after_success:
  - ./ci/after_success.sh
