language: rust

sudo: required

rust:
  - 1.32.0
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: beta
    - rust: nightly

env:
  global:
    - RUSTFLAGS="-D warnings"
    - FEATURES="blas serde-1 docs"

cache: cargo

addons:
  apt:
    update: true
    packages:
      - libopenblas-dev
      - gfortran
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev
      - libiberty-dev
      - libgsl0-dev

before_script:
  - ./ci/before_script.sh

script:
  - ./ci/script.sh

after_success:
  - ./ci/after_success.sh
