[package]

name = "ndarray"
version = "0.14.0"
edition = "2018"
authors = [
  "bluss",
  "Jim Turner"
]
license = "MIT OR Apache-2.0"
readme = "README-crates.io.md"

repository = "https://github.com/rust-ndarray/ndarray"
documentation = "https://docs.rs/ndarray/"

description = "An n-dimensional array for general elements and for numerics. Lightweight array views and slicing; views support chunking and splitting."

keywords = ["array", "data-structure", "multidimensional", "matrix", "blas"]
categories = ["data-structures", "science"]

build = "build.rs"

exclude = ["docgen/images/*"]

[lib]
name = "ndarray"
bench = false
test = true

[dependencies]
num-integer = { version = "0.1.39", default-features = false }
num-traits = { version = "0.2", default-features = false }
num-complex = { version = "0.3", default-features = false }

rayon = { version = "1.0.3", optional = true }

approx = { version = "0.4", optional = true , default-features = false }

# Use via the `blas` crate feature!
cblas-sys = { version = "0.1.4", optional = true, default-features = false }
blas-src = { version = "0.6.1", optional = true, default-features = false }

matrixmultiply = { version = "0.2.0", default-features = false}
serde = { version = "1.0", optional = true }
rawpointer = { version = "0.2" }

[dev-dependencies]
defmac = "0.2"
quickcheck = { version = "0.9", default-features = false }
approx = "0.4"
itertools = { version = "0.9.0", default-features = false, features = ["use_std"] }

[features]
default = ["std"]
# Enable blas usage
# See README for more instructions
blas = ["cblas-sys", "blas-src"]

# Old name for the serde feature
serde-1 = ["serde"]

# These features are used for testing
test-blas-openblas-sys = ["blas"]
test = ["test-blas-openblas-sys"]

# This feature is used for docs
docs = ["approx", "serde", "rayon"]

std = ["num-traits/std", "matrixmultiply/std"]

[profile.release]
[profile.bench]
debug = true

[workspace]
members = ["ndarray-rand", "serialization-tests", "blas-tests"]
exclude = ["numeric-tests","ensure_no_std"]

[package.metadata.release]
no-dev-version = true
tag-name = "{{version}}"

[package.metadata.docs.rs]
features = ["docs"]
