[package]

name = "ndarray"
version = "0.4.1"
authors = ["bluss"]
license = "MIT/Apache-2.0"

repository = "https://github.com/bluss/rust-ndarray"
documentation = "http://bluss.github.io/rust-ndarray/"

description = "An N-dimensional array for general elements and for numerics. Lightweight array views and slicing. Supports both uniquely owned and shared copy-on-write arrays similar to numpy’s ndarray. `rblas` is an optional dependency."

keywords = ["array", "data-structure", "multidimensional", "matrix", "blas"]

build = "build.rs"

[lib]
name = "ndarray"
bench = false
test = false

[build-dependencies]
rustc_version = "0.1.3"

[dependencies.num]
version = "0.1.30"
features = ["complex"]
default-features = false

[dependencies.itertools]
version = "0.4.6"

[dependencies.rustc-serialize]
version = "0.3.16"
optional = true

[dependencies]
blas-sys = { version = "0.5", optional = true, default-features = false }

# rblas is deprecatedish
rblas = { version = "0.0.13", optional = true }

[features]

assign_ops = []

blas = ["blas-sys"]
blas-openblas-sys = [
    "blas",
    "blas-sys/openblas",
    "blas-sys/openblas-provider/system-openblas",
]

# This feature is used for testing
all = ["blas-openblas-sys", "rustc-serialize"]

[profile.release]
[profile.bench]
debug = true
