[package]

name = "ndarray"
version = "0.10.0"
authors = ["bluss"]
license = "MIT/Apache-2.0"

readme = "README.rst"

repository = "https://github.com/bluss/rust-ndarray"
documentation = "https://docs.rs/ndarray/"

description = "An N-dimensional array for general elements and for numerics. Lightweight array views and slicing; views support chunking and splitting."

keywords = ["array", "data-structure", "multidimensional", "matrix", "blas"]
categories = ["data-structures", "science"]

build = "build.rs"

[lib]
name = "ndarray"
bench = false
test = false

[dependencies.num-traits]
version = "0.1.32"
default-features = false

[dependencies.num-complex]
version = "0.1.32"
default-features = false

[dependencies.itertools]
version = "0.6.0"

[dependencies.rustc-serialize]
version = "0.3.20"
optional = true

[dependencies]
# Use via the `blas` crate feature!
blas-sys = { version = "0.6.5", optional = true, default-features = false }
matrixmultiply = { version = "0.1.13" }

[dependencies.serde]
# Use via the `serde-1` crate feature!
version = "1.0"
optional = true

[dev-dependencies]
defmac = "0.1"

[features]
# Enable blas usage
# See README for more instructions
blas = ["blas-sys"]

# Serde 1.0
serde-1 = ["serde"]

# These features are used for testing
blas-openblas-sys = ["blas"]
test = ["blas-openblas-sys"]

# This feature is used for docs
docs = ["rustc-serialize", "serde-1"]

[profile.release]
[profile.bench]
debug = true

[package.metadata.release]
no-dev-version = true

[package.metadata.docs.rs]
features = ["docs"]
