[package]
name = "ndarray-rand"
version = "0.6.0"
authors = ["bluss"]
license = "MIT/Apache-2.0"

repository = "https://github.com/bluss/rust-ndarray"
documentation = "https://docs.rs/ndarray-rand/"

description = "Constructors for randomized arrays. `rand` integration for `ndarray`."

keywords = ["multidimensional", "matrix", "rand", "ndarray"]

[dependencies]
rand = "0.3.14"
ndarray = { version = "0.10.0", path = ".." }
